"""products

Creates the catalogue table and imports the 16 products the website listed
until now (app/data/initial_products.json, exported from the web app's
content), published.

Revision ID: eca8f00b8872
Revises: e56f6191876e
Create Date: 2026-10-09 21:17:56.533344+00:00

"""

import json
from collections.abc import Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eca8f00b8872"
down_revision: str | Sequence[str] | None = "e56f6191876e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("unit", sa.String(length=8), nullable=False),
        sa.Column("summary_sq", sa.String(length=240), nullable=False),
        sa.Column("summary_en", sa.String(length=240), nullable=False),
        sa.Column("description_sq", sa.Text(), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("image", sa.String(length=300), nullable=True),
        sa.Column("pack_sizes_kg", sa.JSON(), nullable=False),
        sa.Column("coverage_min_m2_per_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("coverage_max_m2_per_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_is_published"), "products", ["is_published"], unique=False)
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    # ### end Alembic commands ###

    rows = json.loads(
        (Path(__file__).resolve().parents[2] / "app" / "data" / "initial_products.json").read_text(
            "utf-8"
        )
    )
    products = sa.table(
        "products",
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("category", sa.String),
        sa.column("unit", sa.String),
        sa.column("summary_sq", sa.String),
        sa.column("summary_en", sa.String),
        sa.column("image", sa.String),
        sa.column("pack_sizes_kg", sa.JSON),
        sa.column("coverage_min_m2_per_kg", sa.Numeric),
        sa.column("coverage_max_m2_per_kg", sa.Numeric),
        sa.column("is_published", sa.Boolean),
        sa.column("position", sa.Integer),
    )
    op.bulk_insert(products, [{**row, "is_published": True} for row in rows])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_index(op.f("ix_products_is_published"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
